config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords, :registrations], controllers: {
  sessions: 'public/sessions'
}
devise_scope :customer do
    get 'customers/sign_up', to: 'public/registrations#new', as: :new_customer_registration
    post 'customers/sign_up', to: 'public/registrations#create', as: :customer_registration
  end
  
    # customer側ルーティング
  scope module: 'public' do
    root 'homes#top'
    resources :products, only: [:show, :index]
    get 'about' => 'homes#about'
    get 'customers/my_page' => 'customers#show'
    patch 'customers/update' => 'customers#update'
    get 'customers/edit' => 'customers#edit'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdrawal' => 'customers#withdrawal'
    resources :genres, only: [:show]

    get 'orders/complete' => 'orders#complete'
    resources :shippings, only: [:index, :create, :destroy, :edit, :update]
    resources :orders, only: [:create, :new, :index, :show]

    post 'orders/confirm' => 'orders#confirm'
    resources :cart_items, only: [:index, :create, :update, :destroy]
    delete "cart_items" => "cart_items#destroy_all"
  end

  namespace :customers do
    get 'orders/about' => 'orders#about', as: 'orders_about'

  end

  # admin側ルーティング
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
    get 'admin' => 'admin#top'
    resources :customers, only: [:index, :edit, :update, :show]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :products, only: [:show, :index, :new, :create, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :orderd_products, only: [:update]
  end

  get "/search" => "products#search"

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :product
  belongs_to :customer

  validates :customer_id, presence: true
	validates :product_id, presence: true
	validates :quantity, presence: true

  def price  #税込み金額
    (product.price.to_i * 1.08).floor
  end

  def sub_price
   self.price*quantity #(product.price.to_i * 1.1).floor * quantity
  end

  def billing_amount #請求金額
    CartItem.billing_amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :shipping_addresses, dependent: :destroy
         has_many :cart_items, dependent: :destroy
         has_many :orders, dependent: :destroy

  def active_for_authentication?
    super && (is_deleted == false)
  end

        

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :products
  
  validates :name, presence: true
  
end

app/models/order.rb
class Order < ApplicationRecord
  

  belongs_to :customer
  has_many :orderd_products, dependent: :destroy

  validates :customer_id, presence: true
  validates :zip_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
  
  enum payment_method: { transfer: 0, credit_card: 1 }
  enum status: { waiting: 0, verification: 1, producing: 2, preparing: 3,shipped: 4 }

end

app/models/orderd_product.rb
class OrderdProduct < ApplicationRecord

  belongs_to :product
  belongs_to :order

  enum order_details: { no_product: 0, waiting: 1, producing: 2, producted: 3 }


end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy

  def add_tax_price
    (self.price * 1.08).round
  end

   def get_image
    (image.attached?) ? image : 'no_image.jpg'
   end
   
   def self.search(search_word) 
    Product.where(["name LIKE(?)"], "%#{search_word}%")
   end
   
   





end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  belongs_to :customer
  
  validates :zip_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
  
  def address_select
    [zip_code, address, name].join(' ')
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!,only: [:create,:edit,:update,:index]

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render 'edit'
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController


  def index
    @orders = Order.all.page(params[:page]).per(10)
  end

  def show
    @order = Order.find(params[:id])
    @orderd_products = OrderdProduct.where(order_id: @order.id)
    @total = 0
    @customer =  @order.customer
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    @orderd_products = @order.orderd_products
    if  @order.status == "verification"
        @orderd_products.each do |orderd_product|
        orderd_product.order_details = "waiting"
        orderd_product.save
      end
    end
    redirect_to admin_order_path(@order)
  end


private

  def order_params
    params.require(:order).permit(:status)
  end


end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin!,only: [:create,:edit,:update,:index, :show, :new]

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_product_path(@product)
    else
      render 'new'
    end
  end

  def index
    @products = Product.all.page(params[:page]).order("id").page(params[:page]).per(10)
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to admin_product_path(@product)
    else
      render 'edit'
    end
  end

  def search
    @products = Product.all.search(params[:keyword])
  end


private

  def product_params
    params.require(:product).permit(:name, :image, :explanation, :genre_id, :price, :is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/products/edit.html.erb
<div class="row">
  <div class="col-xs-12 mx-auto my-5 ">
    <div class="row">
      
    <%= form_for(@product, url: admin_product_path) do |f| %>
      <h2 class="bg-light w-75 text-center">商品編集</h2>
      <br>
      <div class="col-xs-6">
        
        <div class="form-group">
          <%= f.label :"商品画像", class: "col-sm-3 control-label" %>
          <%= f.file_field :image, accept: "image/*" %>
        </div>
        
        <div class="form-group">
          <%= f.label :"商品名", class: "col-sm-3 control-label" %>
          <%= f.text_field :name, class: "col-sm-9 form-control-static name" %>
        </div>
        
        <div class="form-group">
          <%= f.label :"商品説明", class: "col-sm-3 control-label" %>
          <%= f.text_area :explanation, class: "col-sm-9 control-label explanation" %>
        </div>
        
        <div class="form-group">
          <%= f.label :"ジャンル", class: "col-sm-3 control-label" %>
          <%= f.collection_select :genre_id, Genre.all ,:id, :name, include_blank: "--選択してください--" %>
        </div>
        
        <div class="form-group">
          <%= f.label :"税抜価格", class: "col-sm-3 control-label" %>
          <%= f.text_field :price, class: "col-sm-3 form-control-static price" %>円
        </div>
        
        <div class="form-group">
          <%= f.label :"商品ステータス", class: "col-sm-3 control-label" %>
          <%= f.select :is_active, [['販売中', true], ['販売停止', false]], prompt: "-- 選択してください --", class: "col-sm-9 is_sale" %>
        </div>
        
        <div class="actions mb-3">
	        <%= f.submit "変更", class: "btn btn-primary pull-right" %>
        </div>
        
      </div>
    <% end %>

    </div>
  </div>
</div>

app/views/admin/products/index.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1 mx-auto my-5">
    <h2 class="head-line title_h2 text-center bg-light w-50 mx-auto">商品一覧</h2>
    <%= link_to new_admin_product_path, class: "btn btn-success btn-lg mb-2 " do %>
      新規商品登録
    <% end %>
    <table class="table table-bordered">
      <thead class="thead-light">
        <tr class="info">
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
        </tr>
      </thead>
      
      <tbody>
			  <% @products.each do |product| %>
  			  <tr>
            <td class="info col-xs-1">
              <%= product.id %>
            </td>
            <td class="text-left">
              <%= link_to admin_product_path(product), class: "btn-link" do %>
                <%= product.name %>
              <% end %>
            </td>
            <td class="text-right col-xs-1">
              ¥<%= product.price.to_s(:delimited) %>
            </td>
            <td class="text-left col-xs-3">
              <%= product.genre.name %>
            </td>
            <td class="col-xs-2">
              <% if product.is_active == true %>
      					<p><i class="fas fa-bullseye red"></i>販売中</p>
      				<% elsif product.is_active == false %>
      					<p><i class="fas fa-bullseye blue"></i>販売停止中</p>
      				<% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
      
    </table>
    <div class="col-5 mx-auto">
     <%= paginate @products %>
    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<div class="row">
  <div class="col-xs-12 mx-auto my-5 ">
    <h2 class="head-line title_h2 text-center bg-light w-75 mx-auto">商品新規登録</h2>

    <%= form_with model:@product, url: admin_products_path, method: :post, class: "form-horizontal" do |f| %>
      <div class="col-xs-4 col-xs-offset-1">
        <div class="img_field">
        </div>
      </div>

      <div class="col-xs-6">
        <div class="form-group">
          <%= f.label :"商品画像", class: "col-sm-3 control-label" %>
          <%= f.file_field :image, accept: "image/*" %>
        </div>

        <div class="form-group">
          <%= f.label :"商品名", class: "col-sm-3 control-label" %>
          <%= f.text_field :name, class: "col-sm-9 form-control-static name" %>
        </div>

        <div class="form-group">
          <%= f.label :"商品説明", class: "col-sm-3 control-label" %>
          <%= f.text_area :explanation, class: "col-sm-9 control-label explanation" %>
        </div>

        <div class="form-group">
          <%= f.label :"ジャンル", class: "col-sm-3 control-label" %>
          <%= f.collection_select :genre_id, Genre.all ,:id, :name, include_blank: "--選択してください--" %>
        </div>

        <div class="form-group">
          <%= f.label :"税抜価格", class: "col-sm-3 control-label" %>
          <%= f.text_field :price, class: "col-sm-3 form-control-static price" %>円
        </div>

        <div class="form-group">
          <%= f.label :"商品ステータス", class: "col-sm-3 control-label" %>
          <%= f.select :is_active, [['販売中', true], ['販売停止', false]], prompt: "-- 選択してください --", class: "col-sm-9 is_sale" %>
        </div>

        <div class="actions col-xs-7 mb-5">
  	      <%= f.submit "新規登録", class: "btn btn-primary" %>
        </div>

      </div>
    <% end %>
  </div>
</div>

app/views/admin/products/show.html.erb
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-3 mx-auto my-5">
    <h2 class="bg-light w-75 text-center">商品詳細</h2><br>
    <%= image_tag @product.get_image, width: '50%', height: '50%' %>
  </div>

    <div class="col-md-3 my-5  ">
      <table class="table">
        <tbody>
          <tr>
            <td>商品名</td>
            <td><%= @product.name %></td>
          </tr>
          <tr>
            <td>商品説明</td>
            <td><%= @product.explanation %></td>
          </tr>
          <tr>
            <td>税込価格<br>(税抜価格)</td>
            <td><%= @product.add_tax_price.to_s(:delimited) %> 円<br>(<%= @product.price.to_s(:delimited) %>) 円</td>
          </tr>
          <tr>
            <td>販売ステータス</td>
            <td>
              <% if @product.is_active  %>
                販売中
              <% else %>
                販売停止中
              <% end %>
            </td>
          </tr>
          <tr>
            <td><%= link_to "編集する", edit_admin_product_path(@product), class: "btn btn-primary" %></td>
          </tr>
        </tbody>
      </table>
    </div>
  <div class="col-md-4"></div>
</div>