config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords, :registrations], controllers: {
  sessions: 'public/sessions'
}
devise_scope :customer do
    get 'customers/sign_up', to: 'public/registrations#new', as: :new_customer_registration
    post 'customers/sign_up', to: 'public/registrations#create', as: :customer_registration
  end
  
    # customer側ルーティング
  scope module: 'public' do
    root 'homes#top'
    resources :products, only: [:show, :index]
    get 'about' => 'homes#about'
    get 'customers/my_page' => 'customers#show'
    patch 'customers/update' => 'customers#update'
    get 'customers/edit' => 'customers#edit'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdrawal' => 'customers#withdrawal'
    resources :genres, only: [:show]

    get 'orders/complete' => 'orders#complete'
    resources :shippings, only: [:index, :create, :destroy, :edit, :update]
    resources :orders, only: [:create, :new, :index, :show]

    post 'orders/confirm' => 'orders#confirm'
    resources :cart_items, only: [:index, :create, :update, :destroy]
    delete "cart_items" => "cart_items#destroy_all"
  end

  namespace :customers do
    get 'orders/about' => 'orders#about', as: 'orders_about'

  end

  # admin側ルーティング
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
    get 'admin' => 'admin#top'
    resources :customers, only: [:index, :edit, :update, :show]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :products, only: [:show, :index, :new, :create, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :orderd_products, only: [:update]
  end

  get "/search" => "products#search"

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :product
  belongs_to :customer

  validates :customer_id, presence: true
	validates :product_id, presence: true
	validates :quantity, presence: true

  def price  #税込み金額
    (product.price.to_i * 1.08).floor
  end

  def sub_price
   self.price*quantity #(product.price.to_i * 1.1).floor * quantity
  end

  def billing_amount #請求金額
    CartItem.billing_amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :shipping_addresses, dependent: :destroy
         has_many :cart_items, dependent: :destroy
         has_many :orders, dependent: :destroy

  def active_for_authentication?
    super && (is_deleted == false)
  end

        

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :products
  
  validates :name, presence: true
  
end

app/models/order.rb
class Order < ApplicationRecord
  

  belongs_to :customer
  has_many :orderd_products, dependent: :destroy

  validates :customer_id, presence: true
  validates :zip_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
  
  enum payment_method: { transfer: 0, credit_card: 1 }
  enum status: { waiting: 0, verification: 1, producing: 2, preparing: 3,shipped: 4 }

end

app/models/orderd_product.rb
class OrderdProduct < ApplicationRecord

  belongs_to :product
  belongs_to :order

  enum order_details: { no_product: 0, waiting: 1, producing: 2, producted: 3 }


end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy

  def add_tax_price
    (self.price * 1.08).round
  end

   def get_image
    (image.attached?) ? image : 'no_image.jpg'
   end
   
   def self.search(search_word) 
    Product.where(["name LIKE(?)"], "%#{search_word}%")
   end
   
   





end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  belongs_to :customer
  
  validates :zip_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
  
  def address_select
    [zip_code, address, name].join(' ')
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!,only: [:create,:edit,:update,:index]

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render 'edit'
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="border border-dark">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-5" href="/"><span><%= image_tag 'logo.png' %> </span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto ">
            <% if admin_signed_in? %>

            <li>
              <%= link_to admin_products_path, class: 'nav-link btn btn-outline-secondary text-dark' do %>
                商品一覧
              <% end %>
            </li>
            <li>

              <%= link_to admin_customers_path, class: 'nav-link btn btn-outline-secondary text-dark' do %>
              会員一覧
              <% end %>
            </li>
            <li>
              <%= link_to admin_orders_path, class: 'nav-link btn btn-outline-secondary text-dark' do %>
              注文履歴一覧


              <% end %>
            </li>
            <li>
              <%= link_to admin_genres_path, class: 'nav-link btn btn-outline-secondary text-dark' do %>
                ジャンル一覧
              <% end %>
            </li>
            <li>
              <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link btn btn-outline-secondary text-dark' do %>
                ログアウト
              <% end %>
            </li>

            <% else %>

            <% if customer_signed_in? %>
            <li class="mt-5">
              ようこそ、<%= current_customer.last_name + current_customer.first_name %>さん！
            </li>
            <li>
              <%= link_to customers_my_page_path, class: 'nav-link btn btn-outline-secondary text-dark' do %>
                マイページ
              <% end %>
            </li>
            <li>
              <%= link_to products_path, class: 'nav-link btn btn-outline-secondary text-dark' do %>
                商品一覧
              <% end %>
            </li>
            <li>
              <%= link_to cart_items_path, class: 'nav-link btn btn-outline-secondary text-dark' do %>
                カート
              <% end %>
            </li>
            <li>
              <%= link_to destroy_customer_session_path, method: :delete, class: 'nav-link btn btn-outline-secondary text-dark' do %>
                ログアウト
              <% end %>
            </li>
              <% else %>
            <li class="nav-item">
              <%= link_to about_path, class: 'nav-link btn btn-outline-secondary text-dark' do %>
                About
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to products_path, class: 'nav-link btn btn-outline-secondary text-dark' do %>
                商品一覧
              <% end %>

            </li>
            <li>
              <%= link_to new_customer_registration_path, class: 'nav-link btn btn-outline-secondary text-dark' do %>
                新規登録
              <% end %>
            </li>
            <li>
              <%= link_to  new_customer_session_path, class: 'nav-link btn btn-outline-secondary text-dark' do %>
                ログイン
              <% end %>
            </li>
            <% end %>
            <% end %>
            </ul><br>
            <div class="pull-right" style="margin-top: 100px;">
             <%= form_with url: search_path, method: :get, local: true do |f| %>
                <%= f.text_field :keyword,placeholder: "検索", class: "search-text"%>
              <% end %>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>
    <footer class="border border-dark bg-white fixed-bottom">
        <div class="container">
          <div class="small text-center text-muted" style="margin: 10px 0;">©ながのケーキ
          </div>
        </div>
</footer>
  </body>
</html>